{{- if eq .Values.mode "central" }}
{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flugschreiber.fullname" . }}
  labels:
    {{- include "flugschreiber.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.secret.upstreamApiKey }}
  {{ $.Values.secret.keys.upstreamApiKey }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.eventsToken }}
  {{ $.Values.secret.keys.eventsToken }}: {{ . | quote }}
  {{- end }}
  {{- if .Values.secret.s3.enabled }}
  {{- with .Values.secret.s3.accessKeyId }}
  {{ $.Values.secret.keys.s3AccessKeyId }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.s3.secretAccessKey }}
  {{ $.Values.secret.keys.s3SecretAccessKey }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.s3.sessionToken }}
  {{ $.Values.secret.keys.s3SessionToken }}: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
